// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBUFHn4IhRLMQMXy0hILihPw4nAm_ZJ8',
    appId: '1:813667414038:web:5cf903db9235497f4e8537',
    messagingSenderId: '813667414038',
    projectId: 'estore-39560',
    authDomain: 'estore-39560.firebaseapp.com',
    storageBucket: 'estore-39560.appspot.com',
    measurementId: 'G-Y8R4FRVVHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcIyyOXrYfItb--iS4TGVWDOdfCIVCDk',
    appId: '1:813667414038:android:2e37de0bb7d1fd1b4e8537',
    messagingSenderId: '813667414038',
    projectId: 'estore-39560',
    storageBucket: 'estore-39560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfvCkXpQkq6A5bG0tO92V5XDE2KP9ZFsI',
    appId: '1:813667414038:ios:57dac1e8a7ebf4524e8537',
    messagingSenderId: '813667414038',
    projectId: 'estore-39560',
    storageBucket: 'estore-39560.appspot.com',
    iosBundleId: 'com.example.eShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfvCkXpQkq6A5bG0tO92V5XDE2KP9ZFsI',
    appId: '1:813667414038:ios:e424abb385db61754e8537',
    messagingSenderId: '813667414038',
    projectId: 'estore-39560',
    storageBucket: 'estore-39560.appspot.com',
    iosBundleId: 'com.example.eShopApp.RunnerTests',
  );
}
